// PM2 Ecosystem Configuration — V1 (DEPRECATED)
// Single source of truth is ecosystem.config.cjs (V2)
// This file kept only for backward compatibility.
//
// Use: pm2 start ecosystem.config.cjs
//
// WARNING: Do not edit this file. Edit ecosystem.config.cjs instead.

module.exports = require('./ecosystem.config.cjs');
